apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-interest-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: simple-interest-calculator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
