apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-interest-calculator
  labels:
    app: simple-interest-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-interest-calculator
  template:
    metadata:
      labels:
        app: simple-interest-calculator
    spec:
      containers:
      - name: simple-interest-calculator
        image: $(registry)/$(imageName):$(tag)   # <-- Dynamic image from pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
